<html>
<head>
<title>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ho! It's News! \\&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[UPDATES]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</title>
<base target="_blank">
<STYLE TYPE="text/css">
td,p,a,center,div,b { font-family: verdana; font-size: 11px; line-height: 15px };
a {text-decoration: none; font-weight: bold}
a:hover {text-decoration: none; color: #000000; cursor: crosshair}
body{scrollbar-face-color: #FFFFCA; 
scrollbar-shadow-color: #FFFFCA; 
scrollbar-highlight-color: #50A2D6; 
scrollbar-3dlight-color: #FFFFCA; 
scrollbar-darkshadow-color: #50A2D6; 
scrollbar-track-color: #FFFFCA; 
scrollbar-arrow-color:  #50A2D6;}
</style>
</head><body topmargin=0 leftmargin=0 bgcolor="#FFFFCA" background="images/updatesbg.jpg" text=#000000 link="#50A2D6" alink="#50A2D6" vlink="#50A2D6"><table border="0" cellpadding="0" cellspacing="0" width="420"  
height="506">

<tr>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates0" src="images/updates_1x1.jpg" width="210" height 
="56" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates1" src="images/updates_1x2.jpg" width="210" height 
="56" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates2" src="images/updates_2x1.jpg" width="210" height 
="56" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates3" src="images/updates_2x2.jpg" width="210" height 
="56" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="2" width="210" height="57">
	<img name="updates4" src="images/updates_3x1.jpg" width="210" height 
="57" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="57">
	<img name="updates5" src="images/updates_3x2.jpg" width="210" height 
="57" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates6" src="images/updates_4x1.jpg" width="210" height 
="56" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates7" src="images/updates_4x2.jpg" width="210" height 
="56" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="2" width="210" height="57">
	<img name="updates8" src="images/updates_5x1.jpg" width="210" height 
="57" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="57">
	<img name="updates9" src="images/updates_5x2.jpg" width="210" height 
="57" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates10" src="images/updates_6x1.jpg" width="210"  
height="56" border="0"></td>
<td rowspan="1" colspan="2" width="210" height="56">
	<img name="updates11" src="images/updates_6x2.jpg" width="210"  
height="56" border="0"></td>
</tr>

<tr>
<td rowspan="1" colspan="1" width="36" height="168">
	<img name="updates12" src="images/updates_7x1.jpg" width="36" height 
="168" border="0"></td>
<td rowspan="1" colspan="2" width="322" height="168"></td>
<td rowspan="1" colspan="1" width="62" height="168">
	<img name="updates14" src="images/updates_7x3.jpg" width="62" height 
="168" border="0"></td>
</tr>

<tr>
<td width="36" height="1">
	<img name="blank" src="blank.gif" width="36" height="1"  
border="0"></td>
<td width="174" height="1">
	<img name="blank" src="blank.gif" width="174" height="1"  
border="0"></td>
<td width="148" height="1">
	<img name="blank" src="blank.gif" width="148" height="1"  
border="0"></td>
<td width="62" height="1">
	<img name="blank" src="blank.gif" width="62" height="1"  
border="0"></td>
</tr>
</table>
<p align="justify" style="width: 320px; position:absolute; left: 37px; top: 340px; z-index:2">