<b>>> Usami Ayaka</b><br><br>
<a href="asummary.php">Summary</a><br>- To start off, a summary of who she is and what she's like.<br><br>
<a href="apersonality.php">Personality</a><br>- What her personality is and her attitude towards others.<br><br>
<a href="alove.php">Loves and Relationships</a><br>- Take a look at who she loves and who's fallen for her.<br><br>
<a href="avoice.php">Seiyuu</a><br>- Who's behind the voice of Ayaka? Find out here.<br><br>