<b>>> Nakano Hiroshi</b><br><br>
<a href="hsummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="hpersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="hlove.php">Loves</a><br>- Who he's in love with and what his relationship with them are.<br><br>
<a href="hfriends.php">Friends</a><br>- Find out who his friends are and his relationship to them.<br><br>
<a href="hvoice.php">Seiyuu</a><br>- Who's behind the voice of Hiro-san? Find out here.