<b>>> K</b><br><br>
<a href="ksummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="kpersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="kfamily.php">Family</a><br>- Information about his family and his relationships with them.<br><br>
<a href="kvoice.php">Seiyuu</a><br>- Who's behind the voice of K? Find out here.