<b>>> Seguchi Mika</b><br><br>
<a href="msummary.php">Summary</a><br>- To start off, a summary of who she is and what she's like.<br><br>
<a href="mpersonality.php">Personality</a><br>- What her personality is and her attitude towards others.<br><br>
<a href="mlove.php">Loves and Relationships</a><br>- Who she's in love with and what her relationship with him is.<br><br>
<a href="mfamily.php">Family</a><br>- Information about her family and her relationships with them.<br><br>
<a href="mvoice.php">Seiyuu</a><br>- Who's behind the voice of Mika? Find out here.