<b>>> Ukai Noriko</b><br><br>
<a href="nsummary.php">Summary</a><br>- To start off, a summary of who she is and what she's like.<br><br>
<a href="npersonality.php">Personality</a><br>- What her personality is and her attitude towards others.<br><br><a href="nfriends.php">Friends</a><br>- Find out who her friends are and her relationship to them.<br><br>
<a href="nvoice.php">Seiyuu</a><br>- Who's behind the voice of Noriko? Find out here.