<b>>> Sakuma Ryuichi</b><br><br>
<a href="rsummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="rpersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="rfriends.php">Friends</a><br>- Find out who his friends are and his relationship to them.<br><br>
<a href="rvoice.php">Seiyuu</a><br>- Who's behind the voice of Ryuichi? Find out here.<br><br>
<a href="rsvoice.php">Singer's Voice</a><br>- Who's behind the awesome <b>singing</b> voice of Ryuichi? *_* Read up here.