<b>>> Shindou Shuichi</b><br><br><a href="shsummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="shpersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="shloves.php">Loves and Relationships</a><br>- Those who have been around him and those who he love.<br><br>
<a href="shfamily.php">Family</a><br>- Information about his family and his relationships with them.<br><br>
<a href="shfriends.php">Friends</a><br>- Find out who his friends are and his relationship to them.<br><br>
<a href="shvoice.php">Seiyuu</a><br>- Who's behind the voice of Shuichi? Find out here.<br><br>
<a href="shsvoice.php">Singer's Voice</a><br>- Who's behind the awesome <b>singing</b> voice of Shuichi? *_* Read up here.