<b>>> Uesugi Tatsuha</b><br><br>
<a href="tasummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="tapersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="tafamily.php">Family</a><br>- - Information about his family and his relationships with them.<br><br>
<a href="tavoice.php">Seiyuu</a><br>- Who's behind the voice of Tatsuha? Find out here.