<b>>> Seguchi Tohma</b><br><br>
<a href="tsummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="tpersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="tloves.php">Loves</a><br>- Who he's in love with and what his relationship with them are.<br><br>
<a href="tfriends.php">Friends</a><br>- Find out who his friends are and his relationship to them.<br><br>
<a href="tvoice.php">Seiyuu</a><br>- Who's behind the voice of Tohma? Find out here.