<b>>> Visitors' Response</b></font><br><br>
<font color=#ffffff face=verdana>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#2) <b>By: <a href="mailto:SageDestiny@aol.com">Sage</a></b><br><b>Regarding:</b> The Future Dubs Issue<br><b>Submitted:</b> Feb. 28th, 2003<br><br>I think your attitude toward the potential of dubs is vastly unfair. 
Gravitation is being dubbed by The Right Stuf, which has been in charge of
Irresponsible Captain Tylor and His and Her Circumstances dubs, which both came
out very well.  Lately, I've been hearing more dubs that I like than ones I
dislike.  Plus, I am in contact with Crispin Freeman, who is a dub superstar,
with a master's degree in acting and a great deal of experience on the stage as
well as in anime, may very well try for the rule of Yuki (with much urging from
his fans, of course ^.^)  And as for the music dubbing...well, they may or they
may not.  But music dubs aren't always so bad, (the Yu Yu Hakusho and Fruits
Basket themes come right to mind), and if you don't like them...well, that's
what DVD is for.  You don't HAVE to watch it in English.
<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.</center>