<b>>> Visitors' Response</b></font><br><br>
<font color=#ffffff face=verdana>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:Super_Otaku_Hoshi@msn.com">Otaku Hoshi</a></b><br><b>Regarding:</b> The Future Dubs Issue<br><b>Submitted:</b> Jan. 10, 2004<br><br>Personally I'm glad its going to be dubbed, I never saw it and I was about to get it on EBay I personally almost always like the original Japanese version better
than dubs.  In fact, the only anime I can think of that I like the dub as much
if not more than the original is Inu-Yasha. <br><br>
I don't mind dubbing, in fact I think it is a really good idea.  It brings more
fans and other things like that.  I just personally don't like it myself most of
the time.  A lot of the time they can take away something that was really
important or attractive in a character's voice when they dub it.  Kurama from
Yu-Yu Hakusho is an excellent example.  His dubbed voice wasn't really bad, it
just took away Megumi-sama's charm.  <br><br>
I am not that familiar with dubbing companies, so I don't know how the
Gravitation dub will turn out.  I do believe that it will be nowhere near as
good as the Japanese version.  To me, Gravitation seems to be a show where it
cannot be captured with dubbing easily. The music would be one thing that would be
hard, and probably the hardest.  I am hoping that they will keep the original
Japanese version for the songs.<br><br>
I usually buy the series fansubbed, and then buy the DVDs that come out here.  I
don't do it to insult dubs.  Usually I do it for a few different reasons.  One
reason would be to see how good the dub was.  I really think it is fun to
compare what they did with the series.  Another reason I get the DVDs is because
I like to watch the series with really good subtitles, if they have that
feature.  I hate it when they only have what they say in the dubbed version as a
subtitle choice.  They did that in Tenchi Universe, and I was really upset.  
I agree with almost everything you said about the dub and other anime dubs. 
Like K making random outbursts in English when he speaks English ^.^  They
usually change the English speaking characters into French speaking characters
(they did this with Pixy Misa from Pretty Sammy) and in one episode of Sailor
Moon.<br><br>
I think that dubs are good if effort is shown in them.  Cardcaptor Sakura had no
effort and no good searching for good voices.  Yu-Yu Hakusho, I think, had a lot
of effort put into it.  They could have done better with Kurama and Yukina
(REALLY Yukina) though.  A lot of anime dubs don't seem to have much effort put
into them, and no time is shown.  It sometimes even seems like they just took
out random stuff and put in random voice actors that they pulled from a hat.
These have been my opinions.  ^_^<br>
******Otaku~Hoshi<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.</center>