<b>>> Visitors' Response</b></font><br><br>
<font color=#ffffff face=verdana>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>
<b>Responses to The Future Dubs</b><br>
<a href="visdub01.php">#1 By Amy<br><br>
<a href="visdub02.php">#2 by Sage</a><br><br>
<a href="visdub03.php">#3 by Taji</a><br><br>
<a href="visdub04.php">#4 by Meis</a>
<ul><li type="square"><a href="visdub04res.php">Amy's response to Meis's opinion</a>
<br><br>
<ul><li type="square"><a href="visdub04res02.php">Meis's response to Amy's response</a></li></li></ul></ul>
<a href="visdub05.php">#5 by Otaku Hoshi</a>
<br><br>
<b>Responses to Another Gravi Season</b><br>
<a href="visseason01.php">#1 By Luna</a><br><br>
<a href="visseason02.php">#2 By Meis</a><br><br>
<a href="visseason03.php">#3 By Otaku Hoshi</a><br><br>
<a href="visseason04.php">#4 By AsnGothic</a>
<br><br>
<b>Responses to Tohma x Yuki</b><br>
<a href="vistohmayuki01.php">#1 By AsnGothic</a>
<br><br>
<b>Reviews of <i>Gravitation DVD Vol. 1: Fateful First Encounter</i></b><br>
<a href="vis1stReview01.php">#1 By Keruri</a><br><br>
<a href="vis1stReview02.php">#2 By Aibon</a><br><br>