<b>>> Eiri Yuki</b><br><br>
<a href="ysummary.php">Summary</a><br>- To start off, a summary of who he is and what he's like.<br><br>
<a href="ypersonality.php">Personality</a><br>- What his personality is and his attitude towards others.<br><br>
<a href="ylove.php">Loves and Relationships</a><br>- Those who have been around him and fallen unexpectedly for him.<br><br>
<a href="yfamily.php">Family</a><br>- Information about his family and his relationships with them.<br><br>
<a href="ypast.php">Past</a><br>- Yuki's past, what he did and what secrets he hides. (<font color=white>Contains spoilers!</font>)<br><br>
<a href="yvoice.php">Seiyuu</a><br>- Who's behind the voice of Yuki? Find out here.<br><br>