<font size=3 face="impact">
Track 12: Breathless</font><br><br>
At the beginning of Track 12, Shuichi goes home and does not find Yuki. Frantic, he goes all over the place trying to find Yuki, stampeding through places and leaving everything in chaos. ^_^ 
<br><br>
The next day, Bad Luck seemed to be disorganized. Shuichi was nowhere to be found and Hiro was tired from a 10 hour phone conversation with Ayaka. <_< Shuichi then walks in, looking dishevelled and dirty. He was asked to go to the president. At his office, Tohma tells him that the reason Eiri disappeared was because of him. Tohma asks Shuichi to stay away from Eiri from now on.
<br><br>
In New York, Yuki goes to the park that Kitazawa was always in. Several flashbacks occur while he stands under the tree where kitazawa used to sit.
<br><br>
Shuichi attempts to go to New York disguised as a suitcase. ^^ K picks Shuichi up from there and takes him back to the studio. Shuichi still needs to concentrate on surpassing Nittle Grasper and making Bad Luck into a legend. At the studio, Shuichi receives a key from Yuki. Shuichi realizes that Yuki is not planning to return and has abandoned everything he left behind. K informs Shuichi that his value is higher than he thinks. Shuichi later tells Hiro that he must learn to surpass Sakuma Ryuichi and do well without getting his confidence from Yuki or Hiro.
<br><br>
In a room, Noriko turns on the TV to a channel featuring Bad Luck. Ryuichi tells Noriko that Bad Luck will not reach them. Shuichi, Hiro, and Suguru come out of the recording room after rehearsing. They see Ryuichi and Noriko coming down the hall. Noriko stops to say hello, but Ryuichi walks right by Shuichi without a glance. Shuichi shouts Ryuichi's name multiple times, but heard nothing the second or third time. Gripping his throat, Shuichi realizes that he's lost his voice...
<br><br>[Track: <a href="1.php">1</a> | <a href="2.php">2</a> | <a href="3.php">3</a> | <a href="4.php">4</a> | <a href="5.php">5</a> | <a href="6.php">6</a> | <a href="7.php">7</a> | <a href="8.php">8</a> | <a href="9.php">9</a> | <a href="10.php">10</a> | <a href="11.php">11</a> | 12 | <a href="13.php">13</a>]<br><br>