<font size=3 face="impact">
Track 13: Got It All</font><br><br>
Track 13: Several gun shots rang in the air, and an old man runs furiously down the snowy street carrying a package. He bumps into a person and falls. Looking up, he sees a shadowy Yuki looking at him out of the corner of his eye. Hearing the police cars and seeing Yuki turning to face him, he fleeds. 
<br><br>
At the studio, Shuichi informs the rest of the crew that he has lost his voice by writing on paper. Sakano freaks out and only stops when K fires a 'harmless gun' at him. He then puts a 'harmless' grenade on top of Shuichi's head and figures out that Shuichi wasn't lying. :P Sakano could not get any help from Tohma, so he takes matters into his own hands. He orders a roomful of sumo wrestlers O.o and tells them to pile onto Shuichi. 
<br><br>
Back at Hiro's home, Hiro tells Shuichi to go to New York quickly and come back quickly. Hiro receives a phone call from Ayaka then and goes into another room. He comes back to find Shuichi gone. 
<br><br>
In the darkened studio, Ryuichi is listening to The Rage Beat when Shuichi came in. Seeing Ryuichi, Shuichi goes back out of the room. Ryuichi tackles Shuichi to the ground, going into cute mode. He grabs Shuichi's sketchpad and started coloring. He sees Shuichi drawing something plain, and he sets to work to make it 'shiny.' Alone in the park later, Shuichi stares at the drawing Ryuichi did and wrote the lyrics to 'Glaring Dream.' He has a flashback of the first time he and Yuki met. 
<br><br>
In New York, Yuki proceeds up a worn flight of stairs to the apartment where he was abused and where he killed Kitazawa. He flashes back to a his younger self with a drunken Kitazawa. Two men come in and Kitazawa accepts ten dollars from them to sexually abuse Eiri. Yuki sits on the floor and lits a cigarette. He notices that the picture sticker that he and Shuichi took together at the amusement park is on the lighter. The building started shaking and Shuichi breaks through the floor in a puppy suit. Yuki was indeed surprised. Shuichi shows him the finished lyrics of Glaring Dream and tells him that no matter where Yuki tries to escape, Shuichi will find him because he loves him. Yuki smiles faintly as he reads the lyrics. He tells Shuichi that he really does have zero talent. ^_^ 
<br><br>
At Zepp Tokyo, Sakano is freaking out because Shuichi hasn't come back yet and the concert is about to start. Noriko tells Ryuichi to sing first, while K is on top of a building scouting for something. A jet plane appears out of the sky and Shuichi is dropped from it. He slams into Zepp Tokyo just as Ryuichi finished Sleepless Beauty. Ryuichi hands him the microphone and tells him to shine...Shuichi then performs the song 'Glaring Dream' to the roaring crowd. 
<br><br>
In the end, Yuki stoops by Kitazawa's grave in the cemetery. He tells Tohma that he is going back home. Tohma turns to the tombstone and sees the engraved words 'I hope to Heaven, his soul is gone.'
<br><br>
THE END
<br><br>[Track: <a href="1.php">1</a> | <a href="2.php">2</a> | <a href="3.php">3</a> | <a href="4.php">4</a> | <a href="5.php">5</a> | <a href="6.php">6</a> | <a href="7.php">7</a> | <a href="8.php">8</a> | <a href="9.php">9</a> | <a href="10.php">10</a> | <a href="11.php">11</a> | <a href="12.php">12</a> | 13]<br><br>