<font size=3 face="impact">
Track 6: Shady Scheme</font><br><br>
Track 6 starts with Yuki having a flashback of him telling Shuichi that he'll be his lover. He is sitting with a editor regarding his newest book. Yuki declines the woman's suggestion that the book should have the title "Lover." 
<br><br>
Out on the street, Shuichi catches up with Yuki and informs him that Bad Luck is going to release their first CD. They find Mika waiting for them at Yuki's house. In the house, Mika and Yuki discuss Yuki's relationships while Shuichi prances around, acting like a puppy. X.x Mika and Shuichi starts to list facts about Yuki and Yuki throws them out of his house.^_^ Mika takes Shuichi to a restaurant and tells him that Yuki has a sense of mistrust and would not take in people easily. She links that Shuichi truely likes Yuki, but he doesn't know anything about Yuki.
<br><br>
At Yuki's house, Yuki admitted that he acted wrongly by throwing Shuichi out of the house. Shuichi becomes excited and confesses that Mika told him that he doesn't know anything about Yuki. Shuichi wants to know everything about him and wants Yuki to tell it himself. Yuki halts Shuichi's queries with a kiss.
<br><br>
Afterwards, he confronts Mika about it on a bridge. Angry, he took his car and drives endlessly to no particular destination, reaching up to 180mph as he flashes back to himself as a young boy shouting 'Yuki' and running towards a young man sitting beneath a tree...He ends up crashing his car and sits against a wall while the ambulance came.
<br><br>
Tachi is incredibly mad that a woman from an interview compared ASk to the rookie band Bad Luck. His rage has been building ever since Bad Luck performed their song on the game show...
<br><br>
Because a tabloid has information and outragious comments about Yuki's relationship with Shuichi, Yuki tells Shuichi to go home and that this is the end of their relationship. Shuichi goes to a small bar with Hiro and cries a river over the break up. Hiro tells Shuichi to choose between whether to cry or be angry, and Shuichi choose to cry.^_^ 
<br><br>
At the ticket counter, Shuichi is confronted by two Bad Luck fans and draws attention to himself. He is chased by crazy fans until Tachi pulls him away from the crowd. Shuichi follows Tachi to his place as they drink and talk. Tachi seems friendly at first, but he reveals what he's really going to do when he shows Shuichi his gang, takes him to a deserted parking lot and threatens and abuses him. Tachi also took photos as evidence to expose what they've done to him if needed. But no matter how Tachi threatens Shuichi, Shuichi refuses to let any harm come to Yuki.
<br><br>
At home, Hiro receives a phone call from Shuichi to come and pick him up in front of Hiro's house. Hiro arrives to see Shuichi bruised and beaten. Shuichi tearfully asks Hiro if it's wrong to love someone...
<br><br>
At NG, Tachi is telling the other members of ASK of how he will see the end of Shuichi and Bad Luck if he exposes the film he took.
<br><br>
Hiro angerily goes to confront Yuki and asks if he remembers his warning earlier of Shuichi having reasons to cry and lose self confidence. He tells Yuki that Shuichi protected him from harm when he was beaten by Tachi. Angered, Yuki asks where Tachi is now...
<br><br>[Track: <a href="1.php">1</a> | <a href="2.php">2</a> | <a href="3.php">3</a> | <a href="4.php">4</a> | <a href="5.php">5</a> | 6 | <a href="7.php">7</a> | <a href="8.php">8</a> | <a href="9.php">9</a> | <a href="10.php">10</a> | <a href="11.php">11</a> | <a href="12.php">12</a> | <a href="13.php">13</a>]<br><br>