<b>>> Avatars</b><br>Avatars are small images/icons that you see on public message boards, often under the person's name on the left side of the posts. Below are a variety of avatars for your usage, just right click and save.<br><br><b>Choose your avatar size:</b><br>= 42 x 42<br>= 50 x 50</a><br>
= <a href="av54.php">54 x 54</a><br>
= <a href="av60.php">60 x 60</a><br>
= <a href="av62.php">62 x 62</a><br>
= <a href="av64.php">64 x 64</a><br><br>