<b>Cliques and Webrings</b><br><br><a href="http://www.vitaminless.com/love" target="_win">adoration </A> * Sakuma Ryuichi
<br>
<a href="http://www.ringsurf.com/netring?ring=dreaming;id=1;action=prev">« </a> <a href="http://www.ringsurf.com/netring?ring=dreaming;action=list">#</a> <a href="http://dream.shounen-ai.org/" target=new>Dreaming Gravitation</a> <a href="http://www.ringsurf.com/netring?ring=dreaming;action=rand">?</a> <a href="http://www.ringsurf.com/netring?ring=dreaming;id=1;action=next">»</a><br>
 <a href="http://www.ringsurf.com/netring?ring=saiorg;id=3;action=prev"><</a>
 <a href="http://www.ringsurf.com/netring?ring=saiorg;action=rand">?</a>
<a href="http://shounen-ai.org/ring">Shounen-ai orG</a>
 <a href="http://www.ringsurf.com/netring?ring=saiorg;action=list">#</a>
 <a href="http://www.ringsurf.com/netring?ring=saiorg;id=3;action=next">></a>
<br><br>
<A HREF="http://www.taikoubou.net/shuu/" target="_blank">
<IMG SRC="http://www.taikoubou.net/shuu/shuu3.gif" WIDTH="30" HEIGHT="30" BORDER="0" ALT="shuu-love!"></A><br><br><center>
<table>
<tr>
<td valign="middle"align="center">
<a target="_top" style="text-decoration: none;" href="http://www.ringsurf.com/netring?ring=30;action=addform">
<img src="http://fablespinner.com/grav/webring/gravi.gif" border=0 alt="Click Here to Join"></a><br>
<a target="_top" style="text-decoration: none;" href="http://www.ringsurf.com/netring?ring=gravi;id=30;action=prev">Prev</a>
<b>|</b>
<a target="_top" style="text-decoration: none;" href="http://www.ringsurf.com/netring?ring=gravi;id=30;action=list">List</a>
<b>|</b>
<a target="_top" style="text-decoration: none;" href="http://www.ringsurf.com/netring?ring=gravi;id=30;action=rand">Random</a>
<b>|</b>
<a target="_top" style="text-decoration: none;" href="http://www.ringsurf.com/netring?ring=gravi;id=30;action=next">Next</a>
</td>
</tr>
</table><br><br>
<a href="http://gravitation.zutiny.org/" target="_blank"><img src="http://dream.shounen-ai.org/site/images/shu2.gif" border=0 alt="I love Shu-chan!"><img src="http://dream.shounen-ai.org/site/images/touma1.gif" border=0 alt="I love Tohma!"><img src="http://dream.shounen-ai.org/site/images/ryu1.gif" border=0 alt="I love Ryu-chan!"></a><br><br>
<table style="border: 1 solid white; cellpadding="0" cellspacing="0" width="190">
<tr><td><table border="0" cellpadding="3" cellspacing="0"><tr><td></td><td><table border="0" cellpadding="0" cellspacing="4"><tr><td align="center"><b>Gravitation Daisuki!</b></td></tr><tr><td align="center" colspan="2" nowrap><a href="http://C.webring.com/wrman?ring=gravitationdais1&amp;addsite" target="_top">Join</a><b> | </b><a href="http://C.webring.com/hub?ring=gravitationdais1&amp;id=7&amp;hub" target="_top">List</a><b> | </b><a href="http://C.webring.com/go?ring=gravitationdais1&amp;id=7&amp;random" target="_top">Random</a><b> | </b><a href="http://C.webring.com/go?ring=gravitationdais1&amp;id=7&amp;prev" target="_top"><b>« Prev</b></a><b> | </b><a href="http://C.webring.com/go?ring=gravitationdais1&amp;id=7&amp;next" target="_top"><b>Next »</b></a></td></tr></table></td></tr></table></td></tr></table>
<br><br>
<table style="border: 1 solid white; cellpadding="0" cellspacing="0" width="190">
<tr><td><table border="0" cellpadding="3" cellspacing="0"><tr><td></td><td><table border="0" cellpadding="0" cellspacing="4"><tr><td align="center"><b>The Gravitation Webring</b></td></tr><tr><td align="center" colspan="2" nowrap><a href="http://q.webring.com/wrman?ring=gravitation&addsite" target="_top">Join</a><b> | </b><a href="http://q.webring.com/hub?ring=gravitation&id=25&hub" target="_top">List</a><b> | </b><a href="http://q.webring.com/go?ring=gravitation&id=25&random" target="_top">Random</a><b> | </b><a href="http://q.webring.com/go?ring=gravitation&id=25&prev" target="_top"><b>« Prev</b></a><b> | </b><a href="http://q.webring.com/go?ring=gravitation&id=25&next" target="_top"><b>Next »</b></a></td></tr></table></td></tr></table></td></tr></table>
<br><br>
<table style="border: 1 solid white; width="190">
<tr><td><table border="0" cellpadding="3" cellspacing="0"><tr><td></td><td><table border="0" cellpadding="0" cellspacing="4"><tr><td align="center"><b>The I Love Gravitation Webring!</b></td></tr><tr><td align="center" colspan="2" nowrap><a href="http://h.webring.com/wrman?ring=ilovegravitation&addsite" target="_top">Join</a><b> | </b><a href="http://h.webring.com/hub?ring=ilovegravitation&id=1&hub" target="_top">List</a><b> | </b><a href="http://h.webring.com/go?ring=ilovegravitation&id=1&random" target="_top">Random</a><b> | </b><a href="http://h.webring.com/go?ring=ilovegravitation&id=1&prev" target="_top"><b>« Prev</b></a><b> | </b><a href="http://h.webring.com/go?ring=ilovegravitation&id=1&next" target="_top"><b>Next »</b></a></td></tr></table></td></tr></table></td></tr></table>
<br><br><a href="http://www.denseminds.com/" target="_blank"><img src="http://dream.shounen-ai.org/site/images/spritesbed.gif" border=0 alt="awww xD"><img src="http://dream.shounen-ai.org/site/images/spritesryui.gif" border=0 alt="Ryuichi-sama *.*"></a>
<br><br>