<b>>> Fanfiction</b><br>
All fanfiction have a rating next to them. Please do not click on the higher ratings if you are underage or are not comfortable with yaoi. If you would like to contribute fanfiction, feel free to <a href="contact.php">submit</a> your fanworks.<br><br>
{<a href="http://dream.shounen-ai.org/media/fanmaybe.html" target="_blank">Maybe, Someday, Smile</a>}<br>
- <b>Extra:</b> :<a href="http://dream.shounen-ai.org/media/fanmaybenote.html" target="_blank">Note : : Dedication</a>:<br> 
- <b>Rating:</b> PG <br>
- <b>Written by:</b> <a href="mailto:violet_eyed_gurl02@hotmail.com">Crush</a><br>
- <b>Description:</b> A Shuichi x Yuki fic, they've broken up and gotten back together once again, with Shuichi singing "Who the Hell are you?" by Madison Avenue. Vignette.
<br><br>
{<a href="http://dream.shounen-ai.org/media/fanpiece.html" target="_blank">Piece of Love</a>}<br>
- <b>Extra:</b> :<a href="http://dream.shounen-ai.org/media/fanpiecenote.html" target="_blank">Note</a>:<br> 
- <b>Rating:</b> PG-13 <br>
- <b>Written by:</b> <a href="mailto:ribbony@yahoo.com">Anomay</a><br>
- <b>Genre:</b> Angst/Romance<br>
- <b>Chapter:</b> /<a href="http://dream.shounen-ai.org/media/fanpiece.html" target="_blank">01</a> /<a href="http://dream.shounen-ai.org/media/fanpiece02.html" target="_blank">02</a> /<a href="http://dream.shounen-ai.org/media/fanpiece03.html" target="_blank">03</a><br> 
- <b>Description:</b> Uesugi Tatsuha, sixteen years old monk-in-training, is a typical senior high school student. However, a chance meeting with the man of his dreams will lead him down a path of heartache and drama. A dark path which would be best left undiscovered.
<br><br>
{<a href="http://dream.shounen-ai.org/media/fanhome.html" target="_blank">Home</a>}<br>
- <b>Extra:</b> :<a href="http://dream.shounen-ai.org/media/fanhomenote.html" target="_blank">Note :: Dedication</a>:<br> 
- <b>Rating:</b> PG <br>
- <b>Written by:</b> <a href="mailto:titillyana@cloverpetals.com">Tasia Chiba</a><br>
- <b>Genre:</b> Reflective Romance<br>
- <b>Description:</b> Yuki reflecting on his feelings of Shuiichi at the end of the series. Vignette.</b><br><br>
{<a href="http://dream.shounen-ai.org/media/fancompare.html" target="_blank">Compare and Contrast</a>}<br>
- <b>Extra:</b> :<a href="http://dream.shounen-ai.org/media/fancomparenote.html" target="_blank">Note</a>:<br> 
- <b>Rating:</b> PG-13<br>
- <b>Written by:</b> <a href="http://destinystruth.net" target="_blank">Mina Lightstar</a><br>
- <b>Genre:</b> Humor<br>
- <b>Description:</b> A rather humorous take of Shuichi and Yuki's bed talks. No lemon or anything in this one, just sweet and funny discussion on a subject that doesn't come up everyday. ^.~</b>
<br><br>
{<a href="http://dream.shounen-ai.org/media/fanwithyou.html" target="_blank">I'm With You</a>}<br>
- <b>Extra:</b> :<a href="http://dream.shounen-ai.org/media/fanwithyounote.html" target="_blank">Note :: Dedication</a>:<br> 
- <b>Rating:</b> PG<br>
- <b>Written by:</b> <a href="mailto:ems4eva@mail.com" target="_blank">SolitudeStarer</a><br>
- <b>Genre:</b> Romance<br>
- <b>Description:</b> It has been two days since Shuichi confronted Yuki at New York. Now he waits
for his return. Can Yuki make it in time before Shuichi breaks down?</b>
<br><br>
{<a href="http://dream.shounen-ai.org/media/fancream.html" target="_blank">Whipped Cream Gone Bad</a>}<br> 
- <b>Rating:</b> R (lime)<br>
- <b>Written by:</b> <a href="mailto:stuck_in_mirror_land@hotmail.com" target="_blank">John</a><br>
- <b>Genre:</b> Romance/Humor<br>
- <b>Description:</b> An anniversary goes awry, dinner gets cold and Whipped Cram Goes Bad!</b>
<br><br>