</td>

<td width=30></td>

<td width="103" valign="top">
<b><font color=black>INFORMATION</font></b></center><br><br><b>Anime -- &raquo;</b><br>
<a href="prelude.php">Prelude</a><br>
<a href="introd.php">Introduction</a><br>
<a href="char.php">Character Profiles</a><br>
<a href="epsumm.php">Ep. Summaries</a><br>
<a href="essays.php">Essays & Articles</a><br>
<a href="kumagoro.php">Kumagoro Tribute</a><br>
<a href="dictionary.php">Dictionary</a><br>
<a href="purchase.php">Purchase Info</a><br><br>
<b>Manga -- &raquo;</b><br>
<a href="manga.php">General Info</a><br>
<a href="http://www.cloverpetals.com/addiction/" target="_blank">Manga Scans</a><br>
<a href="purchase.php">Purchase Info</a><br>
<a href="creator.php">About the Creator</a><br>
<a href="interview.php">Creator Interview</a><br><br>
<b>OAVs</u> -- &raquo;</b><br>
<a href="oavgeneral.php">General Info</a><br>
<a href="oavsumm.php">OAV Summaries</a><br>
<a href="purchase.php">Purchase Info</a><br><br><br>
	
<center><b><font color=black>ENTERTAINMENT</font></b></center><br><b>Media -- &raquo;</b><br>
<a href="images.php">Images<br>
<a href="music.php">Music</a><br>
<a href="lyrics.php">Lyrics</a><br>
<a href="aicons.php">AIM Icons</a><br>
<a href="avatars.php">Avatars</a><br>
<a href="icons.php">LJ Icons</a><br>
<a href="wallpapers.php">Wallpapers</a><br>
<a href="skins.php">Winamp Skins</a><br><br>
<b>Interact -- &raquo;</b><br>
<a href="fanworks.php">Fanworks</a><br>
<a href="polls.php">Polls</a><br>
<a href="poll.php">Next Song Poll</a><br>
<a href="cosplay.php">Cosplay</a><br>
<a href="http://dream.ainoyume.net/media/quiz" target="_blank">Character Quiz</a><br><br>
<b>Games -- &raquo;</b><br>
<a href="tictactoe.php">Tic Tac Toe</a><br>
<a href="http://dream.ainoyume.net/media/hangman.html" target="_blank">Hangman</a><br>
<a href="http://dream.ainoyume.net/media/memory.html" target="_blank">Memory</a><br>
<a href="http://dream.ainoyume.net/media/puzzle.html" target="_blank">Jigsaw Puzzle</a><br><br>

<b><font color=black>SITE RELATED</font></b><br><br>
<a href="updates.php">Updates</a><br>
<a href="layout.php">Layout Info</a><br>
<a href="contact.php">Contact</a><br>
<a href="credits.php">Credits</a><br>
<a href="links.php">Links Out</a><br>
<a href="linkdtd.php">Link DtD</a><br>
<a href="http://dream.ainoyume.net/ring">DtD Webring</a><br>
<a href="cliques.php">Cliques & etc</a><br>
<a href="http://dtd.ainoyume.net/cgi-bin/guestbook.cgi" target="_blank">Guestbook</a><br><br>
<a href="http://dream.ainoyume.net/main.html">Graphics Intense</a><br><br>
</td>
</tr>
</table>
</div>

<img src="images/lite_bottom.jpg">
<table align=center width=660 cellpadding=5><tr><td>

<div style="float:left;">&copy; <a href="http://dream.ainoyume.net" target="_top">Dare to Dream</a> </div>
<div style="float:right;">Part of the <a href="http://ainoyume.net" target="_blank">AinoyumeNET</a> collection</i>	
<p>

</td></tr></table>