<html>
<head>
<title>Dare to Dream ; a fan tribute to Gravitation</title>
<link rel="stylesheet" href="main.css" />
<script type="text/javascript" src="switch.js" /></script>
<META NAME="KEYWORDS" CONTENT="gravitation, gravi, anime, manga, yaoi, shounen-ai, Shindou Shuichi, Eiri Yuki, Fujisaki Suguru, Seguchi Tohma, Mika, Sakuma Ryuichi, Nakano Hiroshi, Hiro, Sakano, K, Crawd Winchester, Uesugi Tatsuha, Ukai Noriko, Usami Ayaka, Aizawa Tachi, Ma-chan, Ken-kun, gravitation wallpapers, gravitation music, gravitation images, gallery, gravitation information, screenshots, games, poll, Maki Murakami, Iceman, The Seeker, Mad Soldiers, Seki Tomokazu, gravitation winamp skins, gravitation lyrics, gravitation fanfics, gravitation fanart, Super Drive, Glaring Dream, Spicy Marmalade, Sleepless Beauty, the Rage Beat, Shining Collection, Blind Game Again, In the Moonlight, Jurejurenaru Kisetsu, Yuutsu Na Seven Days, Kotani Kinya, No Style, Love Stuff"> 
<META NAME="DESCRIPTION" CONTENT="A general site dedicated to the anime Gravitation. Has in depth information, images, music, wallpapers, polls, games, and much more.">
</head>
<body>

<script><!-- Hide this script from old browsers --
document.write('<img src="' + image + '" border="0" " alt="' + alto + '">')
// -- End Hiding Here -->
</script>


<div id="content">
<table width=600><tr><td valign=top>