<b>>> LJ Icons</b><br> <a href="http://livejournal.com" target="_blank">Livejournal</a> (LJ) Icons are the 100x100 user pictures you see associated with each person's post. Even the basic LJ accounts have at least 6 icons. Below are some Gravitation-oriented LJ Icons for your enjoyment. If you do use these, please give <b>credit</b> by linking back to <a href="http://dream.ainoyume.net">Dare to Dream</a>. Please also <b>do not direct link</b> to these images. If you would like to donate Gravitation LJ Icons that you've made, please feel free to <a href="http://ainoyume.net/contact">contact</a> me. Thank you and enjoy.
<br><br>
<center>

<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/ai.png"> 
<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/ryuichi3.png"> 
<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/ryuichi4.png"> 
<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/shu01.png"> 
<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/shu02.png"> 
<img class="ss" src="http://i20.photobucket.com/albums/b214/ecatalina/Gravi/shuichi.png">
<br><br>