<b>&raquo; Interview with Ms. Maki Murakami</b><p>
Ms. Murakami rarely does interviews, but she has graciously provided her time to conduct an interview at an anime convention held in Spain in 2005. The original interview was in Catalan (spoken in Andorra, Spain, France and Italy), but the English translation has kindly been provided courtesy of <a href="http://asami-chan.livejournal.com/" target="_blank">Asami-chan</a>. Thank you!
<br><br>
<a href="http://www.edicionesglenat.es/reportajes/?item=17">Original interview in Catalan + pictures</a><br>
Special thanks to the <a href="http://www.catalandictionary.org/eng">English-Catalan dictionary</a>
<br><br>
<b>How did your life changed after the success of Gravitation?</b><br>
“It hasn’t changed at all. I still have a similar life just like the one I had when I was an apprentice.”
<br><br>

<b>What do you think was the cause for the great acceptance from the readers towards gravitation?</b><br>
There’s something different in gravitation from other series of the Yaoi gender, and it has a very important touch of humor: from a funny point of view that isn’t usual in this type of mangas. It’s a more light, less adult than other shonen ai titles.
<br><br>

<b>Who had been your influences at the time of drawing and narrating stories?</b><br>
"I’m not used to reading manga, but there’s a mangaka from my country that is (from?) Okada Aami I am very influenced in what is the drawing, but over all the way of writing stories. On the other side, I really like the videogames and the role playing games. The cinema is also one of my great hobbies. The ones I watch the most are the great movies of Hollywood that has a lot of special effects, like Independence Day. Many ideas for my mangas also come from here."
<br><br>

<b>Did you have any trouble or received any critique for the fact that Gravitation explains a love story between men?</b><br>
“No, no. I don’t have any problem of this kind. If there was some trouble about this I wouldn’t be able to talk of this subject so openly in the series.”
<br><br>
(This comes like a side note or a narration, I'm not really sure)
<i>At one month of the original series, Maki and her group of assistants (in Japan is common that a mangaka of a certain success has their own assistants) go for a more adult version of Gravitation titled Remix. It is the called Doujinshi.</i>
<br><br>

<b>Why have you decided to do the Doujinshi Remix?</b><br>
(laughs and turns red/blushes) “Remix has more strong and spicy images. The real intention was to put those kinds of scenes on the original series, but it was not possible because of the editorial rules in which the manga was running. This was to satisfy the pure necessity of seeing a version with this kind of scenes, not because of my like of drawing it.”
<br><br>

<b>Is it difficult to handle the dramatic situation of the series in the moments of humor in gravitation?</b><br>
Actually my forte isn’t drawing tragic or serious scenes. In fact, I immediately add a joke scene. For example, I can’t stand a scene that is to romantic or deep. I can’t make it longer because immediately appears a comical scene.
<br><br>

<b>Do you inspire yourself in real life people at the time of creating characters?</b><br>
No, I don’t grab a model from real life when I create the characters. They all come from the imagination.
<br><br>

<b>What do you think of the animated versión of Gravitation?</b><br>
Truth to be told is that I don’t have much to do with this version. Neither have I seen many episodes. I have no idea about animation. I only draw the manga and if there’s an occasion that a company brings the series in another formant, like novels, for example, I’ll be completly charmed.
<br><br>

<small><i>(Here she is asked about what she thinks about the anime/manga convention in Spain, and saying she likes it, but doesn’t have much time to go around because of her agenda and stuff. I didn’t translate it because I thought it was kinda irrelevant. Thought, I will translate it if someone asks for it.)</i></small>
<br><br>


<b>What are your projects after Gravitation?</b><br>
“I’m doing a manga that will be handed soon: Gamerz Heaven. It’s a love story between boys that happens in the world of videogames. It was published in a magazine, but I got so tired that I decided to take a break. I’m also trying to do a second part for Gravitation.”
<br><br>

<b>What do you like the most about being a mangaka?</b><br>
“Mmmm... I think is the fact that you can express a feeling that you have. A feeling that you have inside and you can demonstrate it in an artistically way. Also, there are more people to who you transmit things and they understand. This kind of contact with the readers is very beautiful.<br><br>
</p>