<b>>> Lyrics: Predilection (Japanese)</b><br><br>
nijuuhachi-ji no yoru wo kiritoru<br>
mado wo toshimetara hajimaru<br>
ichido shikaketara tokenai wana wo<br>
ma ni awanai PROTECTION<br>
<br>
tatoeba kimi wo kizutsuketai<br>
jiorama ni tojikomete<br>
tataitemita tte sakendetemo<br>
kikoenai sa PREDILECTION<br>
<br>
iki mo dekinai<br>
joukyou shita de wa<br>
sugureta ai wo musaboru<br>
<br>
*can't get enough       kotoba yori mo motto<br>
don't let me down     tashika ni misete hoshii<br>
one more night          kasuka ni kizutsuita<br>
kimi wo mitsumeru me      sono saki ni...<br>
<br>
uragiru tame ni umaretekita<br>
kuchibiru wo togisumase<br>
muimi na rikutsu ni mata muragaru<br>
orokashisa ni  PREDILECTION<br>
<br>
nasu sube mo nai<br>
kono heya kara<br>
hayaku sukuidashite yo<br>
<br>

**can't get enough       utsukushii mayonaka<br>
   don't let me down     hashiritsuzukete mo mata<br>
   one more night          nigerenai no wa dare?<br>
   kizukitaku mo nai      sono shinjitsu<br>
   can't get enough        kanashige na kao kara<br>
   don't let me down     itami sae fukuetara<br>
   one more night          junsui na ai dake<br>
   tookunai mirai           kanaeru sa<br>
<br>
hajimari sae<br>
ushinawareta<br>
owaranai geemu wo shiyou<br>
<br>
*repeat<br>
**repeat<br><br>