<b>>> Lyrics: No Style (Japanese)</b><br><br>
Furidashita totsuzen no ame ni    sekasareru [akuseru]<br>
omae no inai [baiku] no se ni    shigamitsuiteru kodoku
<br><br>
kami sae mo yurusanai ai ni    futari miserareteta <br>
ore ni wakare tsugeru mae ni    [joushiki] nante sutero yo
<br><br>
~shin'nyuufukinshi no kiken na kono koi ni   oretachi mou ichido dake<br>
onaji yume, kaketemiyou ze!
<br><br>
*I've NO STYLE!!    jiyuu no    I've NO STYLE!!    tsubasa de<br>
torimodoshite miseru    omae to kasaneta kodou<br>
I've NO STYLE!!    omae no    I've NO STYLE!!    subete de<br>
atsuku sawagu karada nagusamete *
<br><br>
furimuita sono hitomi ga    mada ore wo matteite kuretara <br>
itsu no hi ka tomadotteta    kuchizuke wo shinaosou
<br><br>
~tashikameau koto    futari ni wa aru no sa...<br>
hadaka no mune ni furete    ari no mama ore wo kanjite 
<br><br>
**I've NO STYLE!!    jiyuu no    I've NO STYLE!!     tsubasa de<br>
kogareru mama    daite dakarete    kimi to ikitai<br>
I've NO STYLE!!    saigo no   I've NO STYLE!!    rakuen<br>
kuchizuke de mezameru It's a "destiny" **
<br><br>
There's nothing you can not do   jounetsu no mama ni<br>
Don't turn your back on it now    tobu no sa<br>
There's nothing you can not do    ato modori wa shinai<br>
Don't turn your back on it now...
<br><br>
repeat * and ** 
<br><br>