<b>>> Lyrics: Predilection (English)</b><br><br>
The night of 28 o’clock is cut off<br>
It starts when the window is closed<br>
When one time it sets up, I don’t wanna unravell it<br>
It is not time for PROTECTION<br>
<br>
The scar I want to be attach is you, for example<br>
Shutting in the diorama,<br>
Shouting, I was trying to hit, passing,<br>
Listening it does not exceed PREDILECTION<br>
<br>
It is not possible, either with a breath,<br>
Uncer circumstance<br>
The unshirk love is superior<br>
<br>
Can’t get enough    It’s more than words<br>
Don’t let me down    I want it showing for sure<br>
One more night    Whether the scar is attached<br>
That first eye which you stare…<br>
<br>
It was born in order to betray<br>
The lip is sharpened, completing<br>
And you crowd in a meaningless reason<br>
In foolishness PREDILECTION<br>
<br>
There is no beam which it forms<br>
From this room<br>
Rescueing quickly,<br>
<br>
Can’t get enough    Beautiful midnight<br>
Don’t let me down    Still running to attach<br>
One more night     Who is not escaping<br>
That truth I would like to be aware…<br>
Can’t get enough    From heavyhearted face<br>
Don’t let me down    When even pain, it can wipe,<br>
One more night    Just pure love<br>
Distant future it grants<br>
<br>
Even starts<br>
It was lost<br>
The game which it doesn’t end, will be done.
<br><br>