<b>>> Lyrics: Spicy Marmalade (Japanese)</b><br><br>
Spicy Marmalade     jidai wa marude<br>
ui himeta kao de     madowaseru <br>
<br>
nani furueteru     kairaku shugisha ga warau<br>
sameta REERU no ue     kizu kazu ni     shiku mareta mirai<br>
<br>
kibasa ga jama suru     jounetsu ga douka shiteru<br>
kanari akumu janai?     taikutsu ga shouwa shiteru<br>
<br>
Spicy Marmalade     hajiketa mama de<br>
kon yori no CHANSU o tsukame<br>
Vanish into the night     jidai wa maru de<br>
ui himeta kao de     madowaseru<br>
<br>
aoi tsuki no SUTEGI     naki dashite hiru ga sakebu<br>
amai BIN no naka jya     chimeiteki jijitsu wa kanchigai<br>
<br>
ikazura ni hoshi gari     hayari o jibun ni hameru<br>
kanari mondai janai?     kyoe ni sae kizukenai<br>
<br>
Spicy Marmalade     jibun no mama de<br>
sabita kusari nara hazuse<br>
Vanish into the night     mitsumeta mama de<br>
kon yori mo yubisaki de maboroshi ni<br>
<br>
Spicy Marmalade     hajikete mama de<br>
kon yori no CHANSU o tsukame<br>
Vanish into the night     kiwadatsu Marmalade<br>
kakugo kimeta naraba     isso<br>
<br>
Spicy Marmalade     jibun no mama de
sabita kusari nara hazuse<br>
Vanish into the night     jidai wa maru de<br>
ui himeta kao de     madowaseru<br><br>