<b>>> Lyrics: Sleepless Beauty (English)</b><br><br>
I've been charmed by your eyes from far away; wake up and wait for me<br>
Call out and break the night's barricade; the crowd comes out of the reflection <br>
<br>
(there is no way out) if you plan to endure the impact<br>
(until it collapses) a projected lie <br>
<br>
Smile as you become reborn and paint your whole body<br>
See the world suddenly burning up miraculously as we met by chance <br>
<br>
I see you haven't changed at all; the petals scatter from the flower<br>
Polish the gem in your hand everyday so it will build up and start over <br>
<br>
(your cold hand) becauase of thorns shed through weariness<br>
(a doused flame) the smoke carries on <br>
<br>
Now tell me where the light is, sketch it as it dances vividly<br>
Guided words overflow and come out in times of fear <br>
<br>
(cry for a way out) (it crumbles down) <br>
<br>
Smile as you become reborn and paint your whole body<br>
See the world suddenly burning up miraculously as we met by chance <br>
<br>
Now tell me where the light is, sketch it as it dances vividly<br>
Guided words overflow and come out in times of fear
<br><br>
(hold me gently, catch me forever, do more until my heart breaks down)<br><br>