<b>>> Lyrics: Super Drive (Japanese)</b><br><br>
itsuno manika bokura, nanige naku de atta<br>
yasashi sayose atte, kakurenbo wa tsuzu no sou sa
<br><br>
No, wanna sell your soul, shareta kiiroi tacchi de<br>
No, forget smile again, itsumo odotte itai dake
<br><br>
hashiri nukeru ashita, aruite wataru bokura<br>
nishi kaze ni no seta, boku no koe todokuno? sou sa
<br><br>
No, wanna sell your sou, otogi hana no sekai de<br>
No, forget smile again, zutto nemutte itai dake
<br><br>
nee  oi kakete, oi kakete, shiroi kaze<br>
nee  koini natte, aini natte, hane hirogetai
<br><br>
nee  ii koto mo, warui koto mo, subete tashite<br>
ni de watte, umaku ikite, toki o koetai
<br><br>
"se-no" dete o tsunai, mizu tamari koe tara<br>
nijiga nozoku sora, akai ito tsunaguno sou sa
<br><br>
No, wanna sell your soul, ameni soppo mukaretemo<br>
No, forget smile again, bokura waratte itai dake
<br><br>
nee, oi kakete, oi kakete, shiroi kaze<br>
nee, koini natte, aini natte, hane hirogetai
<br><br>
nee, ii koto mo, warui koto mo, subete tashite<br>
ni, de watte, umaku ikite, toki o koetai
<br><br>
toki o koetai<br><br>