<b>>> Lyrics: Rage Beat (English)</b><br><br>
With a terrified look in the eyes, spit those irritated feelings into the fickle wind
The signal that melted into the cracked roadway is leaving only a scar behind.
<br><br>
Before the drowsy noise blurs away tomorrow [or "the future?"],
chase after those ambitiously resounding footsteps. 
<br><br>
That unfulfillable emotion that never settles down somewhere--
just decide to ignore it, then overtake it.
Aim for the loophole in this shy, trembling society,
for the place we keep struggling towards. I want new world.
<br><br>
If you bare your claws at your swarming anxieties, you'll be snapped back by unfamiliar lies,
and the unbearable* times will adorn the rust-covered roads with agitation**
<br><br>
(*to me, moteamasu sounds more extreme and desperate than "lingering" - pushed to the brink of something...)
(** I think we both misread warubirezu ni the first time... warubireru = fearless, calm, composed; then take it and turn that upside down with the -zu ni / "without doing" ending...)
<br><br>
Stuff your bag with nothing but velvet coins.
We don't need a map of the maze-like dreams.
<br><br>
From the tidal-wave's pounding rhythm 
to the glittering silver passion, it's all just temptation's strategic pull*
Your fragile eyes beat on the door we can go through
as we still keep on searching. You just a new world
<br><br>
*trying to keep with waves/water/tides image there, like being caught in an undertow, but not sure if that's the best way to phrase it...
<br><br>
I can still hear the accumulated tears carving their paths into Main Street,
warping the sound of those footsteps.
<br><br>
That unfulfillable emotion that never settles down somewhere--
just decide to ignore it, then overtake it.
Aim for the loophole in this shy, trembling society,
for the place we keep struggling towards. I want new world. <br><br>