<b>>> Lyrics: Glaring Dream (English)</b><br><br>
The whisper that dissolves into the bustling crowd<br>
makes the memories scattered underfoot blur together. 
<br><br>
The blazing of the street where I walk about lost (glaring one way)<br>
illuminates me as coldly as though it freezes. 
<br><br>
The cold times make dreams fall like rain and slip through my hands.<br>
When I woke up from the countless wishes, you are reflected in a shimmering 
illusion -- the silhouette whose faint smile leads me along. 
<br><br>
Even if the gentleness that tells about only what makes anxiety flow<br>
had fulfilled eternity, I still don't want tomorrow. 
<br><br>
The words that I have to give to you are (it's talk to myself)<br>
falling into an everyday routine, even without shadows. 
<br><br>
With a trembling finger, I gather up the dreams; without even breathing <br>
on them, they're crumbling.<br>
Even the certain things are too unreliable; if I believe in something, can I be with you again?<br>
It's whitely vanishing, the silhouette of that day. 
<br><br>
Looking up at that palely-dyed season (Life Winter Dream)<br>
I, who stopped to stand still, am swept away. 
<br><br>
The wind blows it out, makes it be left behind; even the yearning is growing numb from the cold in my heart. 
<br><br>
The cold times drift about in dreams, but are caught and held in your hands.<br>
When I woke up from the countless wishes, you are reflected in a shimmering 
illusion -- the silhouette whose faint smile leads me along. 
<br><br>