<b>>> Lyrics: No Style (English)</b><br><br>
The sudden start of the downpour of rain makes the acceleration go faster<br>
Loneliness is clinging to the back of the motorcycle without you on it. <br>
<br><br>
Together we were enchanted by a love that even the gods won't forgive.<br>
Before telling me you're leaving me, let's throw away common sense and anything 
like it. 
<br><br>
~In this love that's like a "No entry allowed" warning sign, let's try just <br>
one more time<br>
to see if we can gamble everything on the same dream! 
<br><br>
* (I've no style!) Upon these (I've no style!) free wings,<br>
show me we can regain that pulsing beat when we're pressed together.<br>
(I've no style!) With everything (I've no style!) that you are,<br>
comfort this hotly clamoring body. 
<br><br>
If you could still wait for me to come back, with those eyes turned away,<br>
someday, let's recreate that bewildered kiss. 
<br><br>
~What we can confirm in each other is that we are together...<br>
Touch my naked heart; feel me just as I am. 
<br><br>
**(I've no style!) upon these (I've no style!) free wings,<br>
in this state of yearning, hold me, let me hold you; I want to go with you<br>
(I've no style!) to the final (I've no style!) paradise<br>
where I'm awakened by your kiss. It's a "destiny." 
<br><br>
(There's nothing you can not do)   Flying<br>
(Don't turn your back on it now)    in a state of passion.<br>
(There's nothing you can not do)    There's no way to go back.<br>
(Don't turn your back on it now...) 
<br><br>
repeat * and **
<br><br>