<b>>> Lyrics: Spicy Marmalade (English)</b><br><br>
Spicy Marmalade even though it's the next era<br>
The face that hides sadness is lead astray <br>
<br>
Why the trembling? The pleasure principle is to laugh<br>
Woke up over reality with many wounds the streets looked gloomy <br>
<br>
This feeling gets in the way  how is it being passionate?<br>
Isn't it like a nightmare?  If you're bored then cheer together <br>
<br>
Spicy Marmalade bursting out at this moment<br>
From now on you have to seize your chance<br>
Vanish into the night just like it's the next era<br>
The face that hides sadness is lead astray <br>
<br>
The moon's wonderful pale  yell to let out the daylight <br>
Inside the sweet bottle is a place like reality misunderstanding  <br>
<br>
The stars in the sky fit in the popular oneself<br>
Isn't it quite a problem?  Being alone even for a day <br>
<br>
Spicy Marmalade I removed the idle chain<br>
Vanish into the night  already stared at the unchanged illusion  <br>
<br>
Spicy Marmalade bursting out at this moment<br>
From now on you have to seize your chance<br>
Vanish into the night the conspicuous Marmalade<br>
Right now from myself  <br>
<br>
Spicy Marmalade I removed the idle chain<br>
Vanish into the night just like it's the next era<br>
The face that hides sadness is lead astray <br>
<br><br>