<b>>> Lyrics: Super Drive (English)</b><br><br>
By chance, we met unconciously<br>
Drawing gentleness together, will this hide-and-seek ever end? <br>
I see. <br>
<br>
No, wanna sell your soul, a stylish class of yellow<br>
No, forget smile again, I just want to dance forever <br>
<br>
The beginning will start tomorrow; as we crossed over<br>
The west winds are starting to lift; have I reached my voice?<br>
I see.  <br>
<br>
No, wanna sell you soul, in this world of fairy tales<br>
No, forget smile again, I will just sleep throughout the painful ordeals <br>
<br>
Hey, chase after it, chase after it, a white breeze<br>
Hey, it becomes love, it becomes love, I want to spread my wings <br>
<br>
Hey, all the good things, all the bad things, add them all together<br>
Divide by two, and live well, I want to exceed time. <br>
<br>
On a large field, a rope appeared, and I gathered everything<br>
A rainbow appeared out the sky, a red thread connected it<br>
I see.<br><br>
No, wanna sell your soul, the rain turned the other way long ago<br>
No, forget smile again, we just laughed through all the pains <br>
<br>
Hey, chase after it, chase after it, a white breeze<br>
Hey, it becomes love, it becomes love, I want to spread my wings <br>
<br>
Hey, all the good things, all the bad things, add them all together<br>
Divide by two, and live well, I want to exceed time. <br>
<br>
I want to exceed time