<b>>> Lyrics: Glaring Dream (Japanese)</b><br><br>
nigiyaka na, hitogomi ni, tokeru, tsubuyaki ga<br>
ashi moto ni, chirabatta, omoide, nijimaseru
<br><br>
mayoi  aruku, machi no kagayaki wa, glaring one way<br>
kogo e sou na, boku o terasu
<br><br>
tsumetai toki ga, yume o furaseru, kono te no naka o, suri nukete<br>
negai kazo e, mezame ta toki ni, yureru maboroshi ni kimi ga utsuru<br>
boku o michibiku, kasu kana, shiruetto
<br><br>
nagasareru, fuan dake o, tsugeru, yasashisa mo<br>
eien ni mita sareta, ashita mo, hoshi kunai
<br><br>
kimi ni todoke ruhazuno kotoba wa, it's talk to myself<br>
kage mo naku, hibi ni ochiru
<br><br>
furueru yubi de, yume o kasaneru, iki mo, dekizuni, kuzureteku<br>
tashi kana koto, futashi kasugite, nani o shinji reba, kimi ni aeru?<br>
shiroku kieteku, ano hi no shiruetto
<br><br>
awaku somaru kisetsu o miageru, Life Winter Dream<br>
tachi domaru, boku o, sarau
<br><br>
kaze ni kisareru, torinoko sareru, mune ni kaji kamu akogaremo
<br><br>
tsumetai toki ga, yume ni tadayou, sono te no naka ni, uketomete<br>
negai kazo e, mezame ta toki ni, yureru maboroshi ni kimi ga utsuru<br>
boku o michibiku, kasu kana, shiruetto<br><br>