<b>>> Lyrics: Rage Beat (Japanese)</b><br><br>
obieta mezuki de iradatsu omoi uwaki na kaze ni hakisutete<br>
hibi-wareta rojou ni toketa SHIGUNARU wa kizuato dake nokoshite-iku<br>
<br>
madoronda NOIZU ga asu o keshi-saru mae ni<br>
yabou ni hibiku kutsuoto o oikakete<br>
<br>
doko ni mo tomaranai<br>
mitasanai Emotion SHIKATO kimete oikose yo<br>
furueteru SHAI na seikai no nuke-michi o neratte<br>
tadoritsuku basho e I Want New World<br>
<br>
muragaru fuan ni tsume o tatereba mishiranu uso ni hajikarete<br>
mote-amasu jikan ga sabitsuita machi o warubirezu ni kazatte-iru<br>
<br>
berubetto no KOIN dake o PAKKU ni tsumete<br>
meiro no you na yume no chizu wa iranai<br>
<br>
saka-maku kodou kara<br>
kirakira gin no Passion kakehiki dake no yuuwaku<br>
kowaresou na kimi no hitomi ga ikeru DOA tataite<br>
sagashi-tsuzukeru You Just a New World<br>
<br>
MEIN SUTORIITO ni kizamu semegi-atta namida ga<br>
ima mo kikoeru kutsuon o hisumaseru<br>
<br>
doko ni mo tomaranai<br>
mitasanai Emotion SHIKATO kimete oikose yo<br>
furueteru SHAI na seikai no nuke-michi o neratte<br>
tadoritsuku basho e I Want New World<br><br>