<b>>> Lyrics: Sleepless Beauty (Japanese)</b><br><br>
tooku de me o hikarasete  mezameru monotachi matte iru<br>
yoru no jouheki  sasowarete  utsurisumu mure no nukegara ni<br>
<br>
(deguchi no nai)  shougeki ni taeru tsumori nara<br>
(kuzureru hodo)  itsuwari o misete<br>
<br>
umarekawareru anata yo  hitori hohoemanaide  hitomi o irodoru<br>
nozonda sekai ga totsuzen  hai ni natte mo  kiseki ni mada  meguriaeru<br>
<br>
(sotto dakishimete  kowasu you ni)<br>
<br>
muku na mama de sarasarete  hanabira o chirasu hana no you ni<br>
migaku houseki  te no naka no  HIBI ni sae kizukihajimeteru<br>
<br>
(tsumetai te ga)  nukeochita toge o hirou kara<br>
(madoromu hi ga)  kusuburitsuzukeru<br>
<br>
ima mo todokanu hikari no yukue  azayaka ni mau  omoi o egakou<br>
michibiku kotoba ga koborete shimawanu you ni  utsuru toki o  osorenaide<br>
<br>
(deguchi mo naku)  (kuzureochiru)<br>
<br>
umarekawari no anata yo  hitori hohoemanaide  hitomi o irodoru<br>
nozonda sekai ga totsuzen  hai ni natte mo  kiseki wa mada  megurikuru<br>
<br>
todokanu hikari no yukue  azayaka ni mau  omoi o egakou<br>
michibiku kotoba ga koborete shimawanu you ni  utsuru toki o  osorenaide
<br><br>
(sotto dakishimete  zutto tsukamaete  motto kokoro made kowasu you ni)<br><br>