<b>>> Polls</b><br><br>The following polls are intended for opinions and fun only XD Please only vote once, the polls are designed to see what the majority of the people favor. Also, please wait a minute for the polls to load, as this page may look empty at first. There are currently 2 polls.<br><br><center>
<SCRIPT LANGUAGE="javaScript" SRC="http://gravitation.freepolls.com/cgi-bin/polls/001/poll.js">
</SCRIPT><br><br>
<SCRIPT LANGUAGE="javaScript" SRC="http://gravitation.freepolls.com/cgi-bin/polls/002/poll.js">
</SCRIPT>