<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="http://www.xanga.com/home.aspx?user=Hammy_chan" target="_blank">Aibon</a></b><br><b>Regarding:</b> Gravitation DVD 1: Fateful First Encounter<br><b>Submitted:July 2nd, 2004</b> <br><br>

I recently bought myself the Gravitation Volume 1 at Suncoast for $30.00. I thought that the DVD was WAY overpriced.
<br><br>
Boy was I wrong.
<br><br>
After finishing the first episode dubbed I was in love. Shuichi Shindou's voice not only fits him SO well, sometimes I think his voice is much better in English than Japanese!
<br><br>
Some of you must be reading this with faces to marvel at this one: 0_o?! Which I don't blame ANY of you for.
<br><br>
The fact is, Shuichi's voice is what I said to my friend sounds more "dopey." His voice was so hilarious in episode three when he's confessing to Hiro about his night with Yuki Eiri the night before. I nearly wet 
myself when he said "I won't teeelll~!"
<br><br>
Shuichi's voice is absolutely MARVELOUS and matches almost exactly with the song, so it really does sound like him singing.
<br><br>
But that's my opinion.
<br><br>
Next, Yuki. Yuki, Yuki, Yuki. You have GOT to love Yuki with those come hither eyes, and now, a deep monotone voice to go with those eyes. Yes, fangirls, his voice is also a very good one in the dubbed version too. Nothing though, can amout to Yuki-sama's body. ^_^
<br><br>
I think the only voice I'm not TOO partial to is...None of them~! In fact, i believe that this is the BEST dub I have ever seen. They made scenes FUNNIER. Is that even POSSIBLE?
<br><br>
Yes, i submit it is <3 ^_^
<br><br>
<3 Love always, 
<br><br>
Aibon
<br><br>
P.S. Yes. this thing was worth EVERY penny.


<br>
<br><center>would you like to review Gravitation DVD Vol. 1: Fateful First Encounter? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.</center>