<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:DarkEternity@hotmail.com">Meis</a></b><br><b>Regarding:</b> The Future Dubs Issue<br><b>Submitted:</b> Sept. 24, 2003<br><br>In my opinion, most animes get butchered when they are dubbed.  I have
yet to see an anime that I like the English voices more than the Japanese ones. 
Some of them do get pretty close though.
<br><br>
As I have read, some people like the English dub more than the Japanese
original.  Now I think that is just wrong.  The Japanese original is always the
best.  And most of the time the peoples opinions are completely false.  Most
likely, if you watch the dub first then the original will sound different.  And
on the comment someone made about not liking to listen the the Japanese
Language...  Grow up.  If you don't like it then don't listen/watch the anime. 
Being small minded is actually comical to people who aren't.  In my humble
opinion, the Japanese language is beautiful.  English sounds sloppy to you once
you learn Japanese.  And if you complain about the subs being bad, then why not
learn Japanese and just listen to it without complaining?  This just proves that
Americans are by far the most stupid race of humans alive.<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>