<b>&raquo; Visitors' Response</b><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:Unicorn1799@aol.com">Amy</a></b><br><b>Regarding:</b> The Future Dubs Issue<br><b>Submitted:</b> Jan. 04, 2003<br><br>Personally I'm glad its going to be dubbed, I never saw it and I was about to get it on EBay when I just had a thought...it just seemed like a duh factor that it was going to dubbed, too much fansubbing going around and its attracting attention.<br><br>
I can't stand when people buy fansubs and then buy the hybrid DVD...FOR WHAT?!?! You already have the series original just keep that and leave your whine reviews to you sites and yourself.
<br><br>
As far as I can tell, the dubbing is being kept under wraps by RightStuf...who were just as surprised as fans when they said their company got rights...
I'm going to end up watching it in English and Japanese cause I find it a waste of money to hold a such a loathing for a dubbing.
<br><br>
I'm so glad I'm not an Anime Purist, an Anime Otaku, or Hardcore Sub watcher. I just like watching anime in any form dub or original, half the time I can't stand listening to the Japanese voices...the Freckles song sounds cuter in English then Japanese (which is WAY OffKey -_-) I downloaded it thinking it was going to be cute like the dub...turns out my ears were wrong. 
<br><br>
Who knows how this will turn out...theres hardly any info, for all anyone knows they could have the original actors and writters and directors working with the dubbing.
Everytime I see some "don't watch the dub review just watch the sub" I end up not getting the series at all, I miss out on a lot cause of that.
<br><br>
I would like to hear an attempt at the songs in English. Yeah I am a sailor moon fan for both dub and original. And why does SM get used all the time in comparing dubbing today is beyond me...grudges I guess.
<br><br>
Who knows...maybe the dub will be like Chance Pop...english dio then switch to the original Japanese singing...-_- I would have liked it if they gave singing the songs in English a chance but due to so many complains, flames, bitching, whining, from the anime community...it never got a chance. 
<br><br>
Anime fans think that flaming and dissing the dub will get them better dubbings...well ask a dub director and it DOES NOT HELP, it just makes the VA's and the Directors bitter.<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>