<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#3) <b>By: <a href="mailto:TajiKamiya14@aol.com">Taji</a></b><br><b>Regarding:</b> The Future Dubs Issue<br><b>Submitted:</b> June 25th, 2003<br><br>Firstly, I'd like to say that Sailor Moon's dub was just fine. S and
Super S were the more superiorly (is that even a word) dub than Classic and R.
Rurouni Kenshin's not all that horrible either. I personally like the sub. And
we can ALL agree Card Captor Sakura went to hell with Nelvana.
<br><br>
In any case, we're talking about RIGHT STUF dubbing the series. The series that
dubbed my favorite series, Kareshi Kanojo no Jijou/His and Her Circumstances
(Kare-Kano)!!! I mean, I love the dub 25 times better than the sub, because the
voices don't fit.
<br><br>
Just sit down and listen to Yukino's dub voice and Yukino's sub voice (she's the
"kanojo" of the title) and you'll see that Atsuko Enomoto didn't really come
close to matching Yukino's spunky, outgoing personality, like Veronica Taylor
did. But that's my opinion.
<br><br>
Anyway, I have high faith that they (Right Stuf) will do a really good job with
the dub.
<br><br>
As for the music...I'd hate not hear Kotani Kinya's voice for the songs, so I
really don't know how Right Stuf will pull this off. I did find Chance Pop
Session interesting in how they left the Japanese singers alone. It gives it a
unique taste.
<br><br>
They did translate and change a song in Kare-Kano into English and I think they
did very well. But...since half of us have watched Gravi via fansubs and have
downloaded the music, it would be weird. I'm not going to argue there.
<br><br>
We'll see how it turns out though.
<br><br>
In conclusion, I just think that you shouldn't put down dubs before you watch
them. Maybe, they'll have an issue of Newtype USA with a promotional Gravitation
DVD really soon and then we can judge. But, right now, let's stay unbiased about
it.
<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>