<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:dolphin_val2@yahoo.com">AsnGothic</a></b><br><b>Regarding:</b> Another Gravi Season<br><b>Submitted:</b> Nov. 3, 2003<br><br>Personally, I think the Gravitation Anime should have been produced by
another company from the start. The artwork doesn't match the manga and they
change a bunch of the sequences and plot. Plus, they skipped a lot of the
necessary information that was in the first manga. And only 13 episodes...they
obviously didn't put enough content into the anime. If there was a new season,
they'd need a new manga. I guess the new season isn't a good idea, but I still
want more...<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>