<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#3) <b>By: <a href="mailto:luna-luna@seishiyue.zzn.com">Luna</a></b><br><b>Regarding:</b> Another Gravi Season<br><b>Submitted:</b> April 26th, 2003<br><br>Well, I think that Maki Murakami (if it was ever decided to make
another season) could make it worth to watch. If the next season can actually
confront new problematic encounters that is..duh..I mean, in the artistic career
you gotta be very cautious ne? For Shuichi, of course and his band.
Anyway my point is, a good manga artist never runs out of ideas or plots, and
everything can be turned around drastically in a story. And yes it's true 13
eps. won't make enough. ^^
<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>