<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:DarkEternity@hotmail.com">Meis</a></b><br><b>Regarding:</b> Another Gravi Season<br><b>Submitted:</b> Sept. 24, 2003<br><br>I think that Gravitation should not continue on the same story line... 
Although that does not mean that I do not want it to continue at all.  I think
something interesting to watch would be a thing of the past.  Something on how
Yuki and Tohma meet.  Something on how Nittle Grasper forms, on how Shuichi and
Hiro became friends, feelings Shuichi and Yuki had growing up.  It would further
explain everything.  I think it would be great.  Another possibility I am fond
of is of a new Gravitation altogether.  A whole new cast of characters.   I
would want the music-like setting to stay and there are so many different
combinations of things related to music that it would be highly possible to
create.<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>