<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By: <a href="mailto:Super_Otaku_Hoshi@msn.com">Otaku Hoshi</a></b><br><b>Regarding:</b> Another Gravi Season<br><b>Submitted:</b> Jan. 10, 2004<br><br>I would love to see more Gravitation, but at the same time, I think it
had such a good ending.  Sure, I would love to see more of Ryuichi and Shuichi,
but it had such a good ending that I wouldn't want anything to go wrong.  One of
the best things about Gravitation, I think, was its wonderful ending.  I loved
everything about it, but the ending was wonderful.  If they made more, it might
ruin something in the ending that I personally enjoyed, and I am sure other fans
out there enjoyed as well.<br>
******Otaku~Hoshi<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>