<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By:</b> <a href="mailto:alc.1993@hotmail.com">TenshiXXX</a><br><b>Regarding:</b> Tohma x Yuki
<br><b>Submitted:</b> Aug. 8, 2006<br><br>I personally don't think that Tohma's being selfish. I know 
some people might say that's because I love the guy, but it isn't. I 
prefer him with K, anyway.(If you find this pairing insane, THIS IS JUST 
MY OPINION.) Tohma isn't really that lucky in love. He has a wife he 
doesn't love in a romantic sense and Shuichi has taken away the one 
person he did love it that way. I'd be pretty crushed too. <br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>