<b>&raquo; Visitors' Response</b></font><br><br>
Below are some visitors' response to some of the issues addressed in the <a href="essays.php">Essays and Articles</a> section. I would like to stress that these are opinions, so I don't want to see flames and such. If you'd like to respond to one of the responses, send it in the feedback form. Otherwise, enjoy. :)<br><br>#1) <b>By:</b> <a href="mailto:dolphin_val2@yahoo.com">AsnGothic</a><br><b>Regarding:</b> Tohma x Yuki
<br><b>Submitted:</b> Nov. 3, 2003<br><br>I might be saying this because I'm a hardcore Shuichi x Yuki fan, but I
think Tohma and Yuki would make better friends. I haven't read the chapter
you're talking about in your article, but it seems like Tohma's being a little
selfish, even if he cares for Yuki. That's my opinion...<br>
<br><center>would you like to comment on this topic? Leave it <a href="http://ainoyume.net/dtd/feedback.html">here</a>.
<br><br>