Track 10: Heads or Tails</font><br><br>
<font face=arial>
Hiro and Shuichi are talking about Hiro's quit of Bad Luck. Hiro tells Shuichi that he doesn't need someone like Hiro to do well, all he needs is Yuki. Hiro admits that he god jealous of Yuki along the way. But he's in love now...with Usami Ayaka. 
<br><br>
Shuichi goes back to Yuki's house, dressed like a battery to avoid the press. <_< He tells Yuki that K is using their relationship to promote Bad Luck. Yuki didn't like what any of them are doing.
<br><br>
At the studio, K is satisfied that Bad Luck debuted at number 2 for their CD. Sakano informs them that Bad Luck will be doing a 30-district tour next and Shuichi will have to make an announcement during an interview regarding Hiro's quit. Shuichi refuses to work without Hiro, but couldn't come up with a good reason why Bad Luck needed to have Hiro technically, because Suguru can fill Hiro's role with his keyboard. 
<br><br>
Later, Shuichi comes out of a room in the radio station and sees Ryuichi at the end of the hall. He turns and goes the other way, but Ryuichi sees him, turns to cute mode and runs after him. Ryuichi chases Shuichi to the top of the station, where Shuichi tells Ryuichi that he doesn't deserve to be friends with him. Ryuichi didn't understand and runs off after Shuichi asks if Nittle Grasper can go on without Tohma or Noriko.
<br><br>
At home, Ayaka visits Hiro and lets him know that she knows Hiro likes her. She tells Hiro that if Bad Luck can sell 1 million albums, she will date him. 
<br><br>
At the interview, Shuichi is suppose to announce Hiro's retirement, but as he went on air, he changed his mind and decided that Bad Luck can't be without Hiro. Suguru was surprised and frustrated at Shuichi's immature behavior. He grabbed Shuichi's collar and shakes him, and in the midst of the commotion, Hiro appears in the back and he and Shuichi reunit happily. Ryuichi appears from under the table, dressed in a bunny costume and announces that Bad Luck has sold 1 million albums. 
<br><br>
At home, Yuki and Tohma are sitting together and watching the interview. In the middle of their talk, Yuki started throwing up blood.
<br><br>
Shuichi catches up with Ryuichi outside the interview room. Shuichi tells Ryuichi that he's sorry for asking weird questions earlier, and now he's not wandering anymore...
<br><br>[Track: <a href="1.php">1</a> | <a href="2.php">2</a> | <a href="3.php">3</a> | <a href="4.php">4</a> | <a href="5.php">5</a> | <a href="6.php">6</a> | <a href="7.php">7</a> | <a href="8.php">8</a> | <a href="9.php">9</a> | 10 | <a href="11.php">11</a> | <a href="12.php">12</a> | <a href="13.php">13</a>]