Track 11: Secret Day</font><br><br>
<font face=arial>
A flashback of Yuki's past is taking place at the beginning of Track 11. A young Tohma is seen running down a street and up a flight of stairs to a darkened room. Tohma sees blood on the floor and a young Eiri sitting on the floor with a gun in his hand, shaken. Tohma holds Eiri in his arms and tries his best to comfort him as Eiri cries uncontrollably. 
<br><br>
Back at the hospital, Tohma sits and awaits for news of Yuki since Yuki threw up blood in the last episode. Mika comes in and sees a troubled Tohma. 
<br><br>
Across town, Shuichi is in the happiest of moods while posing for the press. Shuichi goes to K and finds out that Yuki was rushed to the hospital after throwing up blood. He goes to the hospital right away.
<br><br>
In Yuki's room at the hospital, Mika and Tohma are persuading Eiri to stop being with Shuichi because it's best for his health. Yuki mentions that he will go to New York.Shuichi overhears the entire conversation and becomes depressed. 
<br><br>
Later at night, Shuichi confesses his problems to Hiro in the park. Hiro gives his advice to Shuichi again, telling him to face Yuki and confront him.
<br><br>
Shuichi takes Hiro's advice and goes to the hospital that night, while Eiri's sleeping. He kisses him and confesses his true feelings to Yuki, thinking that he was asleep. Yuki was infact awake and hears Shuichi. Shuichi tells him that he will die of Yuki goes away. Yuki comforts him and tells him not to take his words so seriously. He goes on to tell Shuichi that he had promised him that he would take him to the amusement park if he sold a million records, and he will keep his promise. 
<br><br>
So, Yuki takes Shuichi to the Odaiba amusement park for a day, letting Shuichi do whatever he wanted, go on roller coasters, play video games at the arcade, taking pictures, etc. Near the end of the day, Yuki and Shuichi are standing by a balcony looking towards the sea, and Yuki decides to tell Shuichi about his past. Yuki pulls out an picture of his younger self and an older male. Yuki tells Shuichi that the man in the picture was the guy Eiri had killed. His name was Yuki Kitazawa, Eiri's former tutor in New York. Eiri ended up taking his pen name from Kitazawa. Kitazawa was kind and friendly, but he had a nasty drinking habit. When he got drunk, he changed personality. Eiri was brutally abused by Kitazawa when he got drunk, and this is the reason Yuki ended up killing him. Shuichi runs off to buy a drink, and Yuki tears the picture into pieces and throws it into the ocean. Shuichi returns to find Yuki gone...
<br><br>[Track: <a href="1.php">1</a> | <a href="2.php">2</a> | <a href="3.php">3</a> | <a href="4.php">4</a> | <a href="5.php">5</a> | <a href="6.php">6</a> | <a href="7.php">7</a> | <a href="8.php">8</a> | <a href="9.php">9</a> | <a href="10.php">10</a> | 11 | <a href="12.php">12</a> | <a href="13.php">13</a>]